# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "iac-provisioner-tfstate-546046686507"
    dynamodb_table = "iac-provisioner-tfstate-lock"
    encrypt        = true
    key            = "dev/terraform.tfstate"
    region         = "eu-north-1"
  }
}
